

spring:
  mail:
    host: smtp.gmail.com
    username: ducnase161841@fpt.edu.vn
    password: reuo hmmc hcuu zzob
    port: 587
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://swp391.mysql.database.azure.com:3306/milkjoy?createDatabaseIfNotExist=true
    username: milkjoyadmin
    password: Swp@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # dùng sqlserver mở đoạn này
#  datasource:
#    url: jdbc:sqlserver://localhost:1433;databaseName=user-management;encrypt=true;trustServerCertificate=true;
#    username: your_sqlserver_username
#    password: your_sqlserver_password
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
server:
  port: 8080
jwt:
  signerKey: mlurGuNCJ+kaZjah59zjCFpJYkCMGYyf0ttiTvlwhJyhjcFaH0pNy/iZ3ySF0yQ5
  tokenExpiryTime: 3600 #in second
  refreshTokenExpiration: 36000 #insecond
springdoc:
  swagger-ui:
    path: /swagger-ui.html
oauth2:
  google:
    client-id: "229203659707-kpvju7vl0mpc0j4gnd2s5eiclnuoaf6q.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000/authenticate"
cloud:
  aws:
    credentials:
      accessKey: AKIA4MTWL3ET3M4ZYFYP
      secretKey: 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
    region:
      static: ap-southeast-1
    s3:
      bucket-name: mutantorchid

