

spring:
  application:
    name: mevabe
  datasource:
    url: jdbc:mysql://localhost:3306/MilkJoy?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
jwt:
  signerKey: mlurGuNCJ+kaZjah59zjCFpJYkCMGYyf0ttiTvlwhJyhjcFaH0pNy/iZ3ySF0yQ5
  tokenExpiryTime: 20 #in second
  refreshTokenExpiration: 120 #insecond
springdoc:
  swagger-ui:
    path: /swagger-ui.html


