version: '3.8'

services:
  mevabe-backend:
    image: cuong3103/milk-joy:first
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://swp391.mysql.database.azure.com:3306/milkjoy?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: milkjoyadmin
      SPRING_DATASOURCE_PASSWORD: Swp@123456
      SPRING_JWT_SIGNERKEY: mlurGuNCJ+kaZjah59zjCFpJYkCMGYyf0ttiTvlwhJyhjcFaH0pNy/iZ3ySF0yQ5
      SPRING_JWT_TOKENEXPIRYTIME: 20
      SPRING_JWT_REFRESHTOKENEXPIRATION: 120
      OAUTH2_GOOGLE_CLIENT_ID: "229203659707-kpvju7vl0mpc0j4gnd2s5eiclnuoaf6q.apps.googleusercontent.com"
      OAUTH2_GOOGLE_CLIENT_SECRET: "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"
      OAUTH2_GOOGLE_REDIRECT_URI: "http://localhost:8081/login/oauth2/code/google"  # Adjust as needed
    networks:
      - milkjoy-network

networks:
  milkjoy-network: