version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: user-management
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mevabe-backend:
    image: cuong3103/milk-joy:first
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user-management?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
    depends_on:
      - mysql

volumes:
  mysql-data:
